import { data } from '../data/edaData';

/**
 * Every number shown on the page comes from data.charts / data, generated by
 * src/web_data.py. Captions carry {token} placeholders so no figure is typed
 * into a translation string, where it could not be checked against the run.
 */
const charts = data.charts;

const TOKENS: Record<string, string> = {
  alerts: data.alerts,
  transactions: data.transactions,
  rate: data.rate,
  columns: data.columns,
  auc: data.auc,
  aucStd: data.auc_std,
  adv: data.adversarial,
  drift: data.drift_verdict,
  kept: data.family_level_kept.join(' + '),
  familiesMeasured: String(data.families_measured),
  familiesUsed: String(data.families_used),
  rejected: String(data.rejected_families),
  chance: String(data.chance_families),
  nullMean: data.null_mean,
  holdoutAuc: data.holdout_auc,
  holdoutCv: data.holdout_cv,
  holdoutRows: data.holdout_rows,
  optimism: data.holdout_optimism,
  gain: data.ensemble_gain,
  bestSingle: data.best_single_model,
  bestSingleAuc: data.best_single_auc,
  historyDays: String(charts.facts.historyDays),
  incomingShare: (charts.facts.incomingShare * 100).toFixed(1) + '%',
  lastTenDaysShare: (charts.facts.lastTenDaysShare * 100).toFixed(1) + '%',
  typeMixGap: (charts.facts.typeMixMaxGap * 100).toFixed(2),
  topType: charts.facts.topType,
  topTypeShare: (charts.facts.topTypeShare * 100).toFixed(1) + '%',
};

/* ---------------------------------------------------------------------------
   Chart geometry. Every series comes from data.charts, generated by
   src/web_data.py out of the training data. This page previously carried
   hand-drawn SVG paths, eight bars for a four-category field, and a
   placeholder box where the target distribution belongs.
   --------------------------------------------------------------------------- */
const PLOT = { x0: 48, x1: 438, yTop: 24, yBase: 214 };

function plotX(index: number, count: number): number {
  if (count <= 1) return PLOT.x0;
  return PLOT.x0 + ((PLOT.x1 - PLOT.x0) * index) / (count - 1);
}

function plotY(value: number, max: number): number {
  if (max <= 0) return PLOT.yBase;
  return PLOT.yBase - (PLOT.yBase - PLOT.yTop) * (value / max);
}

function linePath(values: number[], max: number): string {
  return values
    .map((v, i) => `${i === 0 ? 'M' : 'L'} ${plotX(i, values.length).toFixed(1)},${plotY(v, max).toFixed(1)}`)
    .join(' ');
}

/** Evenly spaced bar slots across the plot area. */
function barLayout(count: number, width = 30) {
  const span = (PLOT.x1 - PLOT.x0) / count;
  return Array.from({ length: count }, (_, i) => ({
    x: PLOT.x0 + span * i + (span - Math.min(width, span - 6)) / 2,
    width: Math.min(width, span - 6),
  }));
}

function compact(n: number): string {
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(n >= 10_000_000 ? 0 : 1) + 'M';
  if (n >= 1_000) return (n / 1_000).toFixed(n >= 10_000 ? 0 : 1) + 'k';
  return String(n);
}

/** Oldest bucket on the left, the alert date on the right. */
const daysToAlert = [...charts.daysBefore].reverse();
const daysMax = Math.max(...charts.daysBefore.flatMap((r) => [r.dismissed, r.escalated]));
const typesMax = Math.max(...charts.types.map((r) => r.n));
const outcomeMax = Math.max(...charts.typesByOutcome.flatMap((r) => [r.dismissed, r.escalated]));
const weeklyMax = Math.max(...charts.weekly.map((r) => r.n));
const targetMax = Math.max(...charts.targetDist.map((r) => r.n));

/** Replace every {token} from the generated data; leave unknown ones visible. */
function fill(template: string): string {
  return template.replace(/\{(\w+)\}/g, (match, key) => TOKENS[key] ?? match);
}

/** Five evenly spaced ticks from 0 to max, positioned on the plot scale. */
function yTicks(max: number, format: (v: number) => string) {
  return [1, 0.75, 0.5, 0.25, 0].map((f) => ({
    y: PLOT.yBase - f * (PLOT.yBase - PLOT.yTop),
    label: format(max * f),
  }));
}

export {
  fill,
  yTicks,
  TOKENS,
  PLOT,
  plotX,
  plotY,
  linePath,
  barLayout,
  compact,
  charts,
  daysToAlert,
  daysMax,
  typesMax,
  outcomeMax,
  weeklyMax,
  targetMax,
};
